/* Rakhaa Investments — document register: filter, search, sort, render.
   Rebuilt as a self-contained module. Reads window.RAKHAA_DOCS (generated by
   build.py into i18n.js) and renders into #docList. No storage APIs,
   no network calls, no dependency on app.js beyond the shared language helper. */
(function () {
  'use strict';

  var DOCS = Array.isArray(window.RAKHAA_DOCS) ? window.RAKHAA_DOCS.slice() : [];

  var el = {
    list: document.getElementById('docList'),
    search: document.getElementById('libSearch'),
    clear: document.getElementById('libClear'),
    sort: document.getElementById('libSort'),
    count: document.getElementById('libCount'),
    empty: document.getElementById('libEmpty'),
    reset: document.getElementById('libReset'),
    reg: document.querySelector('.doc-reg')
  };
  if (!el.list) return;

  var state = { cat: 'all', q: '', sort: 'new' };
  var tabs = Array.prototype.slice.call(document.querySelectorAll('.lib-tab'));

  /* ----------------------------------------------------------- language ---- */
  function lang() {
    return (window.RakhaaLang && window.RakhaaLang.get()) || 'ar';
  }
  function tr(key) {
    return (window.RakhaaLang && window.RakhaaLang.tr(key)) || '';
  }
  function isEN() { return lang() === 'en'; }

  /* --------------------------------------------------------- formatting ---- */
  // Sizes are shown from the real byte count of the shipped PDF.
  function fmtSize(bytes) {
    var n = Number(bytes) || 0;
    if (!n) return '';
    var mb = n / 1048576;
    if (mb >= 1) return trimZero(mb.toFixed(1)) + ' ' + tr('lib_mb');
    return String(Math.max(1, Math.round(n / 1024))) + ' ' + tr('lib_kb');
  }
  function trimZero(s) { return s.replace(/\.0$/, ''); }

  function langLabel(v) {
    if (v === 'both') return tr('lib_lang_both');
    return v === 'en' ? tr('lib_lang_en') : tr('lib_lang_ar');
  }

  function hasYear(v) { return /^\d{4}$/.test(String(v)); }

  function esc(s) {
    return String(s).replace(/&/g, '&amp;').replace(/</g, '&lt;')
      .replace(/>/g, '&gt;').replace(/"/g, '&quot;');
  }

  /* -------------------------------------------------------------- search --- */
  // Fold Arabic orthography so "المكتبه" matches "المكتبة" and harakat are ignored.
  function norm(s) {
    return String(s)
      .toLowerCase()
      .replace(/[\u064B-\u0652\u0640]/g, '')
      .replace(/[\u0622\u0623\u0625]/g, '\u0627')
      .replace(/\u0649/g, '\u064A')
      .replace(/\u0629/g, '\u0647')
      .replace(/[\u0660-\u0669]/g, function (d) {
        return String(d.charCodeAt(0) - 0x0660);
      })
      .replace(/[^\p{L}\p{N}]+/gu, ' ')
      .trim();
  }

  // How people actually phrase each topic, so a category still answers a query
  // that never appears in any document title.
  var SYNONYMS = {
    laws: 'تشريع تشريعات قانون قوانين لائحة لوائح عقوبات جنائي تجارة تجاري مدني تحكيم legislation law laws code commercial civil arbitration penal',
    investment: 'استثمار استثمارات استثماري تمويل مالي مصرفي بنوك بنك شركات حوافز ضمانات investment investments finance financial banking companies incentives',
    labour: 'عمل عمال عمالة عامل موظف موظفين توظيف تأمينات labour labor employment worker workers social insurance',
    tax: 'ضريبة ضرائب ضريبي ضريبية دخل قيمة مضافة إجراءات منازعات tax taxes taxation income vat value added dispute procedures',
    ip: 'ملكية فكرية علامة علامات تجارية اختراع براءة مؤلف نشر intellectual property trademark patent copyright'
  };

  function catWords(key) {
    var D = window.RAKHAA_I18N || {};
    return [key, ((D.ar || {})['cat_' + key] || ''), ((D.en || {})['cat_' + key] || ''),
      (SYNONYMS[key] || '')].join(' ');
  }

  function allWords(hay, q) {
    return q.split(' ').every(function (w) { return hay.indexOf(w) !== -1; });
  }

  /* --------------------------------------------------------------- sorting -- */
  function byYear(dir) {
    return function (a, b) {
      // Undated documents sit at the end of the list either way round, rather
      // than leading the "oldest first" order on a year we do not have.
      var ka = hasYear(a.year), kb = hasYear(b.year);
      if (ka !== kb) return ka ? -1 : 1;
      var ya = Number(a.year) || 0, yb = Number(b.year) || 0;
      if (ya !== yb) return dir * (yb - ya);
      return title(a).localeCompare(title(b), isEN() ? 'en' : 'ar');
    };
  }
  function title(d) { return isEN() ? d.en : d.ar; }

  var SORTS = {
    new: byYear(1),
    old: byYear(-1),
    az: function (a, b) { return title(a).localeCompare(title(b), isEN() ? 'en' : 'ar'); },
    long: function (a, b) { return (Number(b.pages) || 0) - (Number(a.pages) || 0); }
  };

  /* ------------------------------------------------------------ selection --- */
  function selection() {
    var pool = DOCS.filter(function (d) {
      return state.cat === 'all' || d.cat === state.cat;
    });

    if (state.q) {
      var q = norm(state.q);
      // Title / year / filename matches win outright; only when a query matches
      // nothing directly do we widen it to the document's topic.
      var direct = pool.filter(function (d) {
        return allWords(norm([d.ar, d.en, d.year, d.file].join(' ')), q);
      });
      pool = direct.length ? direct
        : pool.filter(function (d) { return allWords(norm(catWords(d.cat)), q); });
    }

    return pool.sort(SORTS[state.sort] || SORTS.new);
  }

  /* ---------------------------------------------------------------- render -- */
  var DL_ICON = '<svg viewBox="0 0 16 16" fill="none" aria-hidden="true">' +
    '<path d="M8 1.5v8m0 0L4.75 6.25M8 9.5l3.25-3.25M2 13.5h12" ' +
    'stroke="currentColor" stroke-width="1.2" stroke-linecap="square"/></svg>';

  function row(doc, i) {
    var t = title(doc);
    var n = String(i + 1).padStart(2, '0');
    var size = fmtSize(doc.bytes);

    return '<article class="doc" id="' + esc(doc.file) + '">' +
      '<span class="doc__n" aria-hidden="true">' + n + '</span>' +

      '<h2 class="doc__t">' + esc(t) + '</h2>' +

      // The meta wrapper is `display: contents` on the wide register, so these
      // four cells sit directly in the row grid; on narrow screens it becomes a
      // real flex line, which lets the download button break onto its own row.
      '<span class="doc__meta">' +
      '<span class="doc__cell doc__cat">' + esc(tr('cat_' + doc.cat)) + '</span>' +

      '<span class="doc__cell doc__year">' +
        (hasYear(doc.year) ? esc(doc.year) : '<i class="doc__nil" aria-hidden="true"></i>') +
      '</span>' +

      '<span class="doc__cell doc__size">' +
        '<b class="doc__pages">' + esc(doc.pages) + ' ' + esc(tr('lib_pages')) + '</b>' +
        (size ? '<i class="doc__bytes">' + esc(size) + '</i>' : '') +
      '</span>' +

      '<span class="doc__cell doc__lang">' + esc(langLabel(doc.lang)) + '</span>' +
      '</span>' +

      '<a class="doc__dl" href="' + encodeURI(doc.file) + '" target="_blank" rel="noopener" ' +
        'aria-label="' + esc(tr('lib_download') + ' — ' + t + ' (' + tr('lib_open') + ')') + '">' +
        DL_ICON + '<span>' + esc(tr('lib_download')) + '</span></a>' +
    '</article>';
  }

  function render() {
    var rows = selection();

    el.list.innerHTML = rows.map(row).join('');

    if (el.count) el.count.textContent = String(rows.length);
    if (el.empty) el.empty.hidden = rows.length !== 0;
    // The column headings describe an empty grid otherwise.
    if (el.reg) el.reg.hidden = rows.length === 0;
    if (el.clear) el.clear.hidden = !state.q;
  }

  /* ---------------------------------------------------------------- events -- */
  function selectTab(tab) {
    state.cat = tab.getAttribute('data-cat') || 'all';
    tabs.forEach(function (o) {
      var on = o === tab;
      o.setAttribute('aria-selected', on ? 'true' : 'false');
      o.tabIndex = on ? 0 : -1;
    });
    render();
  }

  tabs.forEach(function (tab, idx) {
    tab.tabIndex = tab.getAttribute('aria-selected') === 'true' ? 0 : -1;
    tab.addEventListener('click', function () { selectTab(tab); });
    // Roving focus: a tablist is expected to move with the arrow keys.
    tab.addEventListener('keydown', function (e) {
      var step = e.key === 'ArrowRight' ? 1 : e.key === 'ArrowLeft' ? -1 : 0;
      if (!step) return;
      if (document.documentElement.dir === 'rtl') step = -step;
      e.preventDefault();
      var next = tabs[(idx + step + tabs.length) % tabs.length];
      next.focus();
      selectTab(next);
    });
  });

  if (el.search) {
    var timer = null;
    el.search.addEventListener('input', function () {
      window.clearTimeout(timer);
      timer = window.setTimeout(function () {
        state.q = el.search.value.trim();
        render();
      }, 120);
    });
    // Escape clears the field the way a search input is expected to behave.
    el.search.addEventListener('keydown', function (e) {
      if (e.key === 'Escape' && el.search.value) { e.preventDefault(); clearSearch(); }
    });
  }

  function clearSearch() {
    if (!el.search) return;
    el.search.value = '';
    state.q = '';
    render();
    el.search.focus();
  }
  if (el.clear) el.clear.addEventListener('click', clearSearch);

  if (el.sort) {
    el.sort.addEventListener('change', function () {
      state.sort = el.sort.value || 'new';
      render();
    });
  }

  if (el.reset) {
    el.reset.addEventListener('click', function () {
      state.q = '';
      if (el.search) el.search.value = '';
      var all = tabs.filter(function (t) { return t.getAttribute('data-cat') === 'all'; })[0];
      if (all) selectTab(all); else render();
    });
  }

  // Titles, category labels and units all change with the language.
  document.addEventListener('rakhaa:lang', render);

  render();

  /* ------------------------------------------------- deep links from home --- */
  // library.html#<file>.pdf — the homepage insights band links straight to a row.
  if (window.location.hash.length > 1) {
    var id = decodeURIComponent(window.location.hash.slice(1));
    var target = document.getElementById(id);
    if (target) {
      window.setTimeout(function () {
        target.scrollIntoView({ behavior: 'smooth', block: 'center' });
        target.classList.add('is-flagged');
        window.setTimeout(function () { target.classList.remove('is-flagged'); }, 2000);
      }, 260);
    }
  }
}());
